### PR TITLE
Add json file acceptance for qgis-server backend

### PR DESCRIPTION
**Pull request by lucernae**
Needed so geonode can save InaSAFE impact summary data (because the file is in JSON format).

### CODE REVIEW

**Comment by lucernae** [comment]
@ismailsunni @Gustry 
I'm not sure where to merge this or is this the correct branch to merge to.
Perhaps we should also merge this to upstream geonode.

**Comment by ismailsunni** [comment]
@lucernae 
well, this branching is not ideal (at least for me).

master --> full history, all commits
qgis_server_backend --> one single commit, merged to geonode master.

I think it's fine to make a PR to this branch, then make a PR immediately to geonode master. So that we only have small change each PR.

Another approach, you make a  PR directly from your repository, then kartoza repo will only need to pull from geonode.

I am not really sure which one is the best. Squashing commit before making a PR is not comfortable for me.

btw, LGTM

**Comment by ismailsunni** [comment]
Hi @lucernae perhaps it's better if you make a PR to geonode repository directly.

**Comment by lucernae** [comment]
Closed. Make another one.

**Pull request closed without merging**
