### PR TITLE
fix thumbnails are squashed

### LINKED ISSUE #374: thumbnails on testing are squashed
fix aspect ratio

child of #457

### PR DESCRIPTION
**Pull request by boney-bun**
change the dimension of getmap request from 250 by 250 into 180 by 240

fix #374

### CODE REVIEW

**Comment by boney-bun** [comment]
here are the example of the new thumbnails.
what do you think @gubuntu ?

screen shot 2018-02-21 at 12 37 02 am
screen shot 2018-02-21 at 12 36 46 am

For comparison, the thumbnails as generated on testing:

screen shot 2018-02-21 at 12 50 55 am
screen shot 2018-02-21 at 12 50 33 am
screen shot 2018-02-21 at 12 50 01 am

**Comment by gubuntu** [comment]
@boney-bun that's looking much better. But the first Madagascar one is looking a bit squashed still. Something is still not quite right.  

@lucernae yes we need to clean up some branches so ours match upstream names (mainly develop)?

@Gustry then the workflow would be that our devs merge into kartoza/geonode and then when we're happy, we merge that into upstream

**Comment by Gustry** [comment]
But is the branch in which we are doing the merge up to date with the latest from upstream? Who is doing the PR upstream (@lucernae on regular basis or @boney-bun as soon as this PR is approved?) Or do you open this PR only to get a review (not going to merge it in kartoza/geonode)

"master-qgis_server": 
`This branch is 109 commits ahead, 206 commits behind GeoNode:master.`

Sorry for these questions. I'm just asking to be sure that we are not going to lose commits by forgetting our own work not merged in upstream later.

**Comment by boney-bun** [comment]
i think these have a more proportional thumbnails:
screen shot 2018-02-21 at 2 02 20 pm

**Comment by boney-bun** [comment]
@Gustry this PR would go to upstream once we are happy. not sure with other commits.

**Comment by gubuntu** [comment]
that still doesn't look right @boney-bun. Compare the aspect ratio of Madagascar in the Madagascar thumbnail with the Madagascar layer in Layers view.

**Comment by boney-bun** [comment]
instead of using a fixed thumbnail proportion, i'm using a simple math to compare between x and y axes. the result will then be used to determine the thumbnail dimension.
I think this is much better now:
screen shot 2018-02-22 at 1 21 20 pm
screen shot 2018-02-22 at 1 21 12 pm

what do you think @gubuntu ?

**Comment by gubuntu** [comment]
why can't you just use the same pathway as geonode with geoserver? we shouldn't have to do anything like that. Have you inspected the standard geonode code and understand the full thumbnail generation pathway? These images are square again rather than the correct and original landscape aspect ratio.

**Comment by lucernae** [comment]
Hi everyone, as for confirmation, We're not going merge the PR into this branch. This branch should be freeze, and PR should be made against upstream geonode. I thought everyone already agree that we're going to bug fix against upstream directly after all features been merged (which is done).
If this is just for the review, then the branch is wrong too. It should be made against 2.7.x (current stable branch of GeoNode) or master (the develop branch of GeoNode).

So, what's the status of this PR? @boney-bun @gubuntu

**Comment by boney-bun** [comment]
@lucernae thanks for the clarification.
it seems that i developed on the wrong branch.
i'll do it on another branch.

**Pull request closed without merging**
