### PR TITLE
include QGIS Server integration in Travis

### PR DESCRIPTION
**Pull request by lucernae**
WIP.

Experiment by using qgis-server docker for integration tests.

### CODE REVIEW

**Comment by Gustry** [comment]
You already did it ! Awesome @lucernae !

**Comment by timlinux** [comment]
Nice! Any reason you still have geoserver trying to set itself up in there?

**Comment by lucernae** [comment]
We still need to test both. So first with geoserver. Second with qgis-server. But, so far I'm not able to disable geoserver in the second run. I need to modify the paver script in there.

**Comment by lucernae** [comment]
Merge this, and gradually unskip the skipped tests.

**Pull request merged**
