### PR TITLE
Fix Layer Detail View for QGIS Server

### PR DESCRIPTION
**Pull request by lucernae**

### CODE REVIEW

**Comment by Gustry** [comment]
Just a side question, shouldn't we make PR to upstream geonode now? Or is still still useful to work against `master-qgis_server`?

**Comment by lucernae** [comment]
Yes. This is for the training though, which needs to be merged quickly. Then I will cherry pick the commit and create similar PR for upstream :)

**Comment by Gustry** [comment]
Oh ok. I was just to know if we were still using that branch. Happy training ;-)

**Comment by lucernae** [comment]
No, I don't want to use this branch anymore if possible :joy:

**Pull request merged**
