### PR TITLE
add downloading qlr layer in the layer detail

### LINKED ISSUE #154: Download a QGIS .qlr file for a layer
Download a QGIS .qlr file for a layer so that it can easily be added into QGIS. This is the reverse of the QGIS Layer file upload tool. For an existing WMS/WFS/WCS layer we will allow the user to download a QGIS .qlr file that can be simply dragged and dropped into the user’s desktop QGIS session and the layer will appear in their layer list.  Implemented for QGIS backend only.

### PR DESCRIPTION
**Pull request by boney-bun**
push to be reviewed and discussed

.qlr is similar to .lyr

fix #154

### CODE REVIEW

**Comment by boney-bun** [comment]
@timlinux you expect not using xml parser and i totally agree with you.
but then i encountered problems, particularly because we expect the qlr (similar to lyr) to be able to download for the first time. I am having problem to use the `qgis` functions in geonode context. we should use them in the `otf-project` instead.
imo, we should add and generate qlr from the beginning, especially when a user uploads the layers for the first time. by doing so, we can add a function in `otf-project` and utilised all the corresponding qgis functions. this way, we won't need to convert the qgs file anymore and it will be much easier to be downloaded at the end point.

the business logic:
* convert `qgs` to `qlr` by removing the `id` attribute in `<layer-tree-layer>`
* i also modify the `<datasource>`  using relative path as it refers to the server path.
* zipped all the layer files on the server and allows them to be downloaded.

once a user finishes downloading the zip file, the user can extract the zip, and clicks on the qlr file. the file will automatically be opened using the qgis app.

below is the illustration of the working code:
adddownloadqlr154

**Comment by lucernae** [comment]
Thank's for the PR. Now we can see how this goes.

As input from me, I will write it on the ticket #154 .

**Comment by gubuntu** [comment]
- we need some UI for choosing between service types. It is a 'Download' UI so what does the user expect when downloading a qlr file? I would say default to WMS now and add WFS or WCS as options in future (we don't have time now)
- also rename the download type in the UI from qlr to 'QGIS Layer file'

**Comment by boney-bun** [comment]
i'll close this PR because no longer relevant.
the proposed one is #320

**Pull request closed without merging**
