### PR TITLE
fix data tab

### LINKED ISSUE #348: Use 'Data' tab properly
# Issue

Why is there a 'Data' link in the layer download section? That you have to click on to get the list of download links... 

# Solution

Remove the tree and show all download links immediately, as in the GeoServer GeoNode

### PR DESCRIPTION
**Pull request by boney-bun**
fix #348

opentabbydefault

### CODE REVIEW

**Comment by Gustry** [comment]
Just asking, shouldn't it go in upstream? so as to keep our fork small compared to upstream

**Comment by boney-bun** [comment]
i'm not sure about it.
if the upstream don't use the `view` Link just like what we do, probably we can make a PR to the upstream.

**Comment by Gustry** [comment]
I don't know if this can be made straight in upstream geonode, you know the code better than me ;-) But I'm worried that it will be very difficult for the geonode upstream community to review if we make a big PR like the previous one. So it's much better to provide to them a very small and atomic PR so that they can review it quickly. My 2 cents ;-)

Maybe @lucernae has some plans about the PR to geonode.

**Comment by boney-bun** [comment]
i got your point @Gustry 
even if the upstream always use the `view` Link, adding the code from this PR can be useful if unexpected stuff happens (i.e.:  the view link can't be generated, something wrong with the layer, etc)

yes, let's hear from @lucernae :)

**Pull request merged**
