### PR TITLE
Add Wagtail for static page

### PR DESCRIPTION
**Pull request by zamuzakki**
For https://github.com/kartoza/IGRAC-GGIS/issues/31. 

Wagtail admin page can be accessed from `/cms`, using the same admin account used to login to Django Admin page. Wagtail page can be accessed from `/pages`

### CODE REVIEW

**Comment by zamuzakki** [comment]
@ann26 I need to read more docs on how to customize the template and where to put it. I have followed https://docs.wagtail.io/en/v2.0/getting_started/tutorial.html for templates styling and locations, but still not working. So when we open the `/page`, it will only show **Disclaimer and Licenses** with white background, no styling at all.

**Comment by zamuzakki** [comment]
**Wagtail Admin:**
Screenshot from 2020-05-26 11-21-59

Screenshot from 2020-05-26 11-21-50

**Wagtail Page:**
Screenshot from 2020-05-26 11-22-03

**Comment by zamuzakki** [comment]
Fix https://github.com/kartoza/IGRAC-GGIS/issues/31.

wagtail

**Comment by ann26** [comment]
hi @zamuzakki please resolve the conflicts and then you can merge. Please use squash and merge. thanks.

**Pull request merged**
