### PR TITLE
Update 2.6.x qgis server

### PR DESCRIPTION
**Pull request by lucernae**
Cherry-picked progress from master-qgis_server

### CODE REVIEW

**Comment by timlinux** [comment]
@lucernae how come we are not using QGIS 2.14 LTR server? Do you need me to build a 2.14 image?

**Comment by timlinux** [comment]
oh or is the 2.6 referring to GeoNode version?

**Comment by Gustry** [comment]
:D Yes he is talking about geonode 2.6

2.7 is the master version of geonode

**Comment by lucernae** [comment]
Will merge this first despite failed CI.
Failed for Geoserver only anyway.

**Pull request merged**
