### PR TITLE
Pull geonode/django docker image before building django

### PR DESCRIPTION
**Pull request by Vampouille**

### CODE REVIEW

**Comment by lucernae** [comment]
Hi @Vampouille , AFAIK docker-compose will automatically pull the image if it's not found in your local image cache.
Is there any specific reason/error on why you want to add it?

**Comment by gubuntu** [comment]
Can we close?

**Comment by Vampouille** [comment]
> Is there any specific reason/error on why you want to add it?

Purpose of this pull is to *update* local image with security fixes from upstream image. So if upstream has changed, it will be pulled.

**Comment by Vampouille** [comment]
> Can we close?

yes you can merge ;-)

**Comment by lucernae** [comment]
Thank's @Vampouille, I think we will close this.
However I personally think this fixes should go to Geonode/geonode repo directly.
If you had the chance, please submit PR to them directly.

**Pull request closed without merging**
