### PR TITLE
Migrate qgis_server code to geonode 2.6.x

### PR DESCRIPTION
**Pull request by lucernae**
I tried to preserve history for now.
But I guess this is needs to be squashed down when we made PR to geonode, resulting all previous commit authorship, gone :'(.

### CODE REVIEW

**Comment by timlinux** [comment]
No problem if you squash everything @lucernae !

**Comment by Gustry** [comment]
No problem for me too !

**Comment by ismailsunni** [comment]
No problem to squash it.
Orange squash :)

**Comment by lucernae** [comment]
I will squash it via github first.

**Pull request merged**
