### PR TITLE
add osm basemap to the thumbnail

### LINKED ISSUE #401: add basemap to the thumbnail
the current thumbnails are a result of only the rendered layers. 
It would be nice if the thumbnails also draw the basemap on the layers' background. so the user can easily see where the layers fit on the map.

child of #457

### PR DESCRIPTION
**Pull request by boney-bun**
fix #401

### CODE REVIEW

**Comment by boney-bun** [comment]
i think this will be a draft PR as I need feedback.
this PR will depend on otf-project.

the PR in action:
basemapthumbs

questions:
- do we need some kind of flag to turn off the basemap on the thumbnails?
- should we add options for various basemap? i only use osm as the basemap.

**Comment by NyakudyaA** [comment]
@boney-bun awesome. I think if QGIS server can do it consistently you need to make a PR upstream to Geonode because Geoserver does not do this consistently as well. 
Geoserver only adds a base map when you manually replace a thumbnail.
* Thumbnail should only have OSM as a base map - We should not complicate things. Unless if you can make a flag that allows a user to specify which base map to use for thumbnails on install of Geonode.
* Thumbnails should also have a base map. it makes them look nice and gives geographical context.

**Comment by gubuntu** [comment]
No you don't need otf to do anything. You just add the basemap layer to your thumbnail request

**Comment by boney-bun** [comment]
@NyakudyaA thanks for your comments.
yes, i agree. we need a simple solution. hence, i'll use the osm for the background of thumbnails.

> I think if QGIS server can do it consistently you need to make a PR upstream to Geonode because Geoserver does not do this consistently as well.

I'm afraid this PR can't bring up to the upstream as the PR will need otf too.

> No you don't need otf to do anything. You just add the basemap layer to your thumbnail request

@gubuntu we need otf to modify the qgs. 
the thumbnail request can't generate basemap without prior information of the basemap in the qgs file. it's a different case from geoserver backend.
solely add basemap layer when making a WMS request to qgis-server won't work.
me and @lucernae had a discussion about this and it needs otf to be part of the solution.

**Comment by gubuntu** [comment]
When GeoServer does add a basemap to a thumbnail how does it achieve that? We can do it the same way with QGIS server backend. 

The Django view can make a request to the backend WMS service, another request to the basemap service with the same parameters and composite (flatten) the two returned images into one thumbbnail image.

**Comment by boney-bun** [comment]
i think the tricky part is in the qgs file.
the qgs is required for both layers and maps in qgis-server perspective.
when making a WMS request to qgis-server for a layer, the server will check both the qgs and the layer parameters in the request .
if the basemap doesn't exist in the qgs, the qgis-server will ignore the basemap eventhough the basemap layer presents in the request parameter. 

in the geoserver case, the WMS request can simply specify the layers parameter in the request. 

that's why @lucernae proposes to handle the qgs since the beginning of its creation (on the otf).

**Comment by lucernae** [comment]
> I'm afraid this PR can't bring up to the upstream as the PR will need otf too.

Upstream also uses the same QGIS Server backend we can put it to upstream of course.

> When GeoServer does add a basemap to a thumbnail how does it achieve that? We can do it the same way with QGIS server backend.

To be honest I don't know how they do this. We already used the same thumbnail generation scheme, WMS request that is sent to GeoServer and QGIS Server is the same, they also both return thumbnail without basemap (transparent background PNG). They must have some code that inject the basemap somehow, because the thumbnail from WMS and map thumbnail that gets displayed have different extent too. So I assume we have to do the same QGIS Server (send the basemap info to QGIS Server).

> The Django view can make a request to the backend WMS service, another request to the basemap service with the same parameters and composite (flatten) the two returned images into one thumbbnail image.

But can we request a basemap layer to QGIS Server when they didn't have the basemap?

**Comment by gubuntu** [comment]
Thanks @lucernae 

I believe they (geoserver backend) do inject the basemap and we should do it the same way.

1. Fetch layer (or map) thumbnail pngs with transparent background via WMS
2. Fetch basemap png from basemap server (e.g. MapSurfer) ___with exactly the same extent and CRS___
3. use or modify `generate_thumbnail_content()` to combine / flatten all the pngs together into the final thumbnail

**Comment by boney-bun** [comment]
i have a rough idea adding basemap without changing otf-project.
we could implement @gubuntu idea, but i think we still need to store a basemap info into a qgs file. 
later, we could call this qgs and overlay the basemap along with a layer using a PIL  function.  
how's that sound @gubuntu @lucernae ?

**Comment by lucernae** [comment]
> we could implement @gubuntu idea, but i think we still need to store a basemap info into a qgs file.

If we still need to store a basemap info into a qgis file, I still think it's better to just modify otf-project so it can return WMS request with the basemap (optionally). It's the easiest to do and least resistance/changes from GeoNode's code.

> 2. Fetch basemap png from basemap server (e.g. MapSurfer) with exactly the same extent and CRS

I'm not sure how this work. At the moment, the basemap were configured from GeoNode and it is a tile layer for map client. I Imagined it is not a WMS. User can also choose which basemap to use from the Map creation UI, so we need to request the basemap accordingly.

**Comment by gubuntu** [comment]
@boney-bun have you asked the community?

@timlinux can you weigh in, this is dragging out

**Comment by boney-bun** [comment]
i'll close this PR as this is no longer valid.

#465 is the replacement.

**Pull request closed without merging**
