### PR TITLE
UI changes

### PR DESCRIPTION
**Pull request by boney-bun**
- change wording for QLR and QGS
- change the filename
- also code refactoring

fix kartoza/geosafe#233

### CODE REVIEW

**Comment by boney-bun** [comment]
*The link for QGIS and QLR as shown in the UI:*
screen shot 2017-09-22 at 11 04 16 am

*The file name is now taken using layer.title (previously: layer.name)*
screen shot 2017-09-22 at 11 19 23 am

**Comment by Gustry** [comment]
Only a suggestion, should we replace space in the file name? by underscore?

Thanks @boney-bun, looks good !

**Comment by gubuntu** [comment]
LGTM

**Comment by boney-bun** [comment]
@Gustry thanks for your comment.
probably we can discuss the underscore in the forum.
for now, i'll merge them

**Pull request merged**
