### PR TITLE
Fix thumbnail to default aspect ratios

### PR DESCRIPTION
**Pull request by lucernae**
fix for #497 #517 

Now, after we got meters unit, we can properly calculate new extent based on GeoNode default aspect ratios: [200, 150] pixels. We used 400, 300 for clarity, because we displayed the basemap. It helps for the label resolutions to become readable.

There are some weird bug though.

Previously, when we request to WMS in QGIS Server, we provided bbox in the format: [ymin,xmin,ymax,xmax] in EPSG:4326.
However, in EPSG:3857, I had to use [xmin,ymin,xmax,ymax] for it to display the correct extent (took me a while to realize). I don't know if this is expected from QGIS Server, cc @gubuntu ?

### CODE REVIEW

**Comment by lucernae** [comment]
Waiting to fix the thumbnail unittests.

**Comment by lucernae** [comment]
Preview:

thumb-ash-fall

**Comment by gubuntu** [comment]
LGTM

@lucernae the swapped coordinate order for geographic CRS is a 'feature' of WMS 1.3.0

**Comment by lucernae** [comment]
> @lucernae the swapped coordinate order for geographic CRS is a 'feature' of WMS 1.3.0

Oh no, this is true... https://gis.stackexchange.com/questions/23347/getmap-wms-1-1-0-vs-1-3-0

Now we used EPSG:3857 directly in the request, so it should be safe now.

**Pull request merged**
